---
title: "Practical_N"
author: "Gerko Vink"
date: "Statistical Programming in R"
output: html_document
---


---

1. **Use the following function to calculate the bootstrapped estimate for the correlation between `age` and `weight` on the `boys` data set. Use `R=1000` bootstrap samples.**

```{r}
corfun <- function(data, i){
  data.sample <- data[i,]
  stat <- cor(data.sample$age, data.sample$wgt, use = "pairwise.complete.obs")
	return(stat)
}
```

---

2. **Explore the contents of the `bootstr.cor` object. For example, use function `attributes()` to see the listed dimensions that are within the `bootstr.cor` object and the `class` of the object.**

---

3. **Plot the histogram of the individual bootstrapped estimates for every bootstrapped sample (i.e. `$t`).**

---

4. **Add a column to boys that indicates whether boys are overweight by taking the boundary `bmi > 25`.** 

---

5. **Bootstrap a $X^2$-test that evaluates the distribution of overweight `ovw` boys over the regions `reg`. **

---

6. **Plot the histogram of the individual bootstrapped estimates for every bootstrapped sample (i.e. `$t`).**

---
 
7. **Do a bootstrap of the regression estimates of the following model:** 

- `lm(wgt ~ age + hgt + I(hgt^2))`

---

8. ** Create a histogram of the individual bootstrapped estimates **

---

9. **Calculate the confidence intervals for **

---

End of Practical

