<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Garcia-Bernardo (adapted from Gerko Vink)">
<meta name="dcterms.date" content="2023-11-27">

<title>Practical B</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Practical_B_walkthrough_files/libs/clipboard/clipboard.min.js"></script>
<script src="Practical_B_walkthrough_files/libs/quarto-html/quarto.js"></script>
<script src="Practical_B_walkthrough_files/libs/quarto-html/popper.min.js"></script>
<script src="Practical_B_walkthrough_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Practical_B_walkthrough_files/libs/quarto-html/anchor.min.js"></script>
<link href="Practical_B_walkthrough_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Practical_B_walkthrough_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Practical_B_walkthrough_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Practical_B_walkthrough_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Practical_B_walkthrough_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#exercises" id="toc-exercises" class="nav-link active" data-scroll-target="#exercises">Exercises</a>
  <ul>
  <li><a href="#exercise-1-4-vectors-and-matrices" id="toc-exercise-1-4-vectors-and-matrices" class="nav-link" data-scroll-target="#exercise-1-4-vectors-and-matrices">Exercise 1-4: Vectors and matrices</a></li>
  <li><a href="#exercise-5-7-data-frames" id="toc-exercise-5-7-data-frames" class="nav-link" data-scroll-target="#exercise-5-7-data-frames">Exercise 5-7: Data frames</a></li>
  <li><a href="#exercise-8-11-readexplore-csv" id="toc-exercise-8-11-readexplore-csv" class="nav-link" data-scroll-target="#exercise-8-11-readexplore-csv">Exercise 8-11: Read/explore CSV</a></li>
  <li><a href="#exercise-12-14-filtering-the-csv" id="toc-exercise-12-14-filtering-the-csv" class="nav-link" data-scroll-target="#exercise-12-14-filtering-the-csv">Exercise 12-14: Filtering the CSV</a></li>
  <li><a href="#exercises-15-17-visualization" id="toc-exercises-15-17-visualization" class="nav-link" data-scroll-target="#exercises-15-17-visualization">Exercises 15-17: Visualization</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Practical B</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Javier Garcia-Bernardo (adapted from Gerko Vink) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<hr>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p>In this practical exercise we are going to play around with the different types of elements in R.</p>
<p>Click on the <code>Code</code> buttons to see the solutions. Please really try before looking at the solution, and ask the instructor if something is not 100% clear.</p>
<p>First, create a new Quarto document for this practical (File -&gt; New File -&gt; Quarto document)</p>
<section id="exercise-1-4-vectors-and-matrices" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-4-vectors-and-matrices">Exercise 1-4: Vectors and matrices</h2>
<hr>
<ol type="1">
<li><strong>Make two vectors: one named <code>vec1</code> with values 1 through 6 and one named <code>vec2</code> with letters A through F. </strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>vec1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>vec2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>To create a vector we used <code>c()</code>, which stands for ‘concatenation’. It is just a series of numbers or letters.</p>
<hr>
<ol start="2" type="1">
<li><strong>Create two matrices, one from <code>vec1</code> and one from <code>vec2</code>. The dimensions for both matrices are 3 rows by 2 columns. </strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mat1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(vec1, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mat2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(vec2, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>To create a matrix we used <code>matrix()</code>. For a matrix we need to specify the dimensions (in this case 3 rows and 2 columns) and the input (in this case <code>vec1</code> or <code>vec2</code>) needs to match these dimensions.</p>
<hr>
<ol start="3" type="1">
<li><strong>Inspect your vectors and matrices. Are all numerical?</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>vec1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5 6</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>vec2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "A" "B" "C" "D" "E" "F"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mat1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mat2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,] "A"  "D" 
[2,] "B"  "E" 
[3,] "C"  "F" </code></pre>
</div>
</div>
<p><code>vec1</code> and <code>mat1</code> contain numbers and <code>vec2</code> and <code>mat2</code> contain characters.</p>
<hr>
<ol start="4" type="1">
<li><strong>Make a matrix from both <code>vec1</code> and <code>vec2</code> using cbind. Inspect this matrix using is.matrix().</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mat3b <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vec1, vec2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.matrix</span>(mat3b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mat3b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     vec1 vec2
[1,] "1"  "A" 
[2,] "2"  "B" 
[3,] "3"  "C" 
[4,] "4"  "D" 
[5,] "5"  "E" 
[6,] "6"  "F" </code></pre>
</div>
</div>
<p>If one or more elements in the matrix represent characters, all other elements are also converted to characters. A matrix is just for either numeric or character elements. Notice that the second approach (the column bind approach from <code>mat3b</code>) returns a matrix where the column names are already set to the name of the bound objects.</p>
<p>To solve the problem of charactered numbers we can create a dataframe. A dataframe is essentially a matrix that allows for character elements. The use of a dataframe is often preferred over the use of a matrix in <code>R</code>, except for purposes where pure numerical calculations are done, such as in matrix algebra. However, most datasets do contain character information and a dataframe would normally be your preferred choice when working with your own collected datasets in R.</p>
<hr>
</section>
<section id="exercise-5-7-data-frames" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-7-data-frames">Exercise 5-7: Data frames</h2>
<ol start="5" type="1">
<li><strong>Make a dataframe called <code>dat3</code> where <code>vec1</code> and <code>vec2</code> are both columns. Name the columns <code>V1</code> and <code>V2</code>, respectively. Use function <code>data.frame()</code>.</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">V1 =</span> vec1, <span class="at">V2 =</span> vec2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dat3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  V1 V2
1  1  A
2  2  B
3  3  C
4  4  D
5  5  E
6  6  F</code></pre>
</div>
</div>
<ol start="6" type="1">
<li><strong>Select 1) the third row, 2) the second column and 3) the intersection of these two in the dataframe <code>dat3</code> that you have created in Question 4. </strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dat3[<span class="dv">3</span>, ] <span class="co">#3rd row</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  V1 V2
3  3  C</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dat3[, <span class="dv">2</span>] <span class="co">#2nd column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "A" "B" "C" "D" "E" "F"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dat3<span class="sc">$</span>V2   <span class="co">#also 2nd column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "A" "B" "C" "D" "E" "F"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dat3[<span class="dv">3</span>,<span class="dv">2</span>] <span class="co">#intersection</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C"</code></pre>
</div>
</div>
<p>The <code>[3,2]</code> index is very useful in ‘R’. The first number (before the comma) represents the row and the second number (after the comma) represents the column. For a vector there are no two dimensions and only one dimension can be called. For example, <code>vec1[3]</code> would yield <code>3</code>. Try it.</p>
<p>Columns can also be called by the <code>$</code> sign, but only if a name has been assigned. With dataframes assigning names happens automatically.</p>
<p>Note that <code>R</code> automatically reports the values the character column can take. This means that the column is indeed a factor (a categorical variable - as it is supposed to be). A useful function to inspect the structure of a dataframe is <code>str()</code>. Try running it.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   6 obs. of  2 variables:
 $ V1: num  1 2 3 4 5 6
 $ V2: chr  "A" "B" "C" "D" ...</code></pre>
</div>
</div>
<p>Inspecting the structure of your data is vital, as you probably have imported your data from some other source. If we, at a later stage, start analyzing our data without the correct measurement level, we may run into problems. One problem that often occurs is that categorical variables (factors in <code>R</code>) are not coded as such.</p>
<hr>
<ol start="7" type="1">
<li><strong>Imagine that the first variable <code>V1</code> in our dataframe <code>dat3</code> is not coded correctly. Instead of digits, it should represent information about cities. Convert the variable to a factor and add the labels Utrecht (corresponding to value 1), New York (value 2), London (3), Singapore (4), Rome (5) and Cape Town (6).</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dat3<span class="sc">$</span>V1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat3<span class="sc">$</span>V1, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Utrecht"</span>, <span class="st">"New York"</span>, <span class="st">"London"</span>, <span class="st">"Singapore"</span>, <span class="st">"Rome"</span>, <span class="st">"Capetown"</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dat3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         V1 V2
1   Utrecht  A
2  New York  B
3    London  C
4 Singapore  D
5      Rome  E
6  Capetown  F</code></pre>
</div>
</div>
</section>
<section id="exercise-8-11-readexplore-csv" class="level2">
<h2 class="anchored" data-anchor-id="exercise-8-11-readexplore-csv">Exercise 8-11: Read/explore CSV</h2>
<hr>
<ol start="8" type="1">
<li><strong>Read the file <code>dataset_boys.csv</code>.</strong></li>
</ol>
<p>First create a folder “data” in your project. Then download it from <a href="https://javier.science/R/#day-1">here</a> and add it to that folder (use Ctrl+S in the browser to download it).</p>
<p>First you need to load the required library to read the CSV (<code>readr</code>). You may need to install it first.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c("readr"),repos = "http://cran.us.r-project.org")</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then you can read the file using the function <code>read_delim()</code> from the <code>readr</code> library</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 748 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): gen, phb, reg
dbl (6): age, hgt, wgt, bmi, hc, tv

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"data/dataset_boys.csv"</span>, <span class="at">delim=</span><span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age   hgt   wgt   bmi    hc gen   phb      tv reg  
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;
1 0.035  50.1  3.65  14.5  33.7 &lt;NA&gt;  &lt;NA&gt;     NA south
2 0.038  53.5  3.37  11.8  35   &lt;NA&gt;  &lt;NA&gt;     NA south
3 0.057  50    3.14  12.6  35.2 &lt;NA&gt;  &lt;NA&gt;     NA south
4 0.06   54.5  4.27  14.4  36.7 &lt;NA&gt;  &lt;NA&gt;     NA south
5 0.062  57.5  5.03  15.2  37.3 &lt;NA&gt;  &lt;NA&gt;     NA south
6 0.068  55.5  4.66  15.1  37   &lt;NA&gt;  &lt;NA&gt;     NA south</code></pre>
</div>
</div>
<p>Alternatively, you can import datasets directly from the internet by running and loading the connection</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#To update</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">url</span>(<span class="st">"https://javier.science/R/Contents/Material/common_datasets/dataset_boys.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>In the above code we store the connection in object <code>con</code> and then load the connectio.</p>
<p>The <code>boys</code> object will be added to your Global Environment. You can now use the <code>boys</code> data by running</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(con, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 748 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): gen, phb, reg
dbl (6): age, hgt, wgt, bmi, hc, tv

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<ol start="9" type="1">
<li><strong>You can explore boys in several ways. In notebooks just write “boys” and run the chunk. You can also use the “Environment” menu to find the data “boys” and double click it. Alternatively write View(boys).</strong></li>
</ol>
<p>Using <code>View()</code> is preferred for inspecting datasets that are large. <code>View()</code> opens the dataset in a spreadsheet-like window (conform MS Excel, or SPSS). If you <code>View()</code> your own datasets, you can not edit the datasets’ contents.</p>
<hr>
<ol start="10" type="1">
<li><strong>Find out the dimensions of the <code>boys</code> data set (use the function dim) and inspect the first and final 6 cases in the data set. </strong></li>
</ol>
<p>To do it numerically, find out what the dimensions of the boys dataset are. Use the function <code>dim()</code></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 748   9</code></pre>
</div>
</div>
<p>There are 748 cases on 9 variables. To select the first and last six cases, use</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>boys[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age   hgt   wgt   bmi    hc gen   phb      tv reg  
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;
1 0.035  50.1  3.65  14.5  33.7 &lt;NA&gt;  &lt;NA&gt;     NA south
2 0.038  53.5  3.37  11.8  35   &lt;NA&gt;  &lt;NA&gt;     NA south
3 0.057  50    3.14  12.6  35.2 &lt;NA&gt;  &lt;NA&gt;     NA south
4 0.06   54.5  4.27  14.4  36.7 &lt;NA&gt;  &lt;NA&gt;     NA south
5 0.062  57.5  5.03  15.2  37.3 &lt;NA&gt;  &lt;NA&gt;     NA south
6 0.068  55.5  4.66  15.1  37   &lt;NA&gt;  &lt;NA&gt;     NA south</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>boys[<span class="dv">743</span><span class="sc">:</span><span class="dv">748</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age   hgt   wgt   bmi    hc gen   phb      tv reg  
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;
1  20.4  189.  59.8  16.8  55.2 &lt;NA&gt;  &lt;NA&gt;     NA west 
2  20.4  181.  67.2  20.5  56.6 &lt;NA&gt;  &lt;NA&gt;     NA north
3  20.8  189.  88    24.6  NA   &lt;NA&gt;  &lt;NA&gt;     NA west 
4  20.8  194.  75.4  20.1  NA   &lt;NA&gt;  &lt;NA&gt;     NA west 
5  20.8  189   78    21.8  59.9 &lt;NA&gt;  &lt;NA&gt;     NA north
6  21.2  182.  76.5  23.1  NA   &lt;NA&gt;  &lt;NA&gt;     NA east </code></pre>
</div>
</div>
<p>or, more efficiently:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age   hgt   wgt   bmi    hc gen   phb      tv reg  
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;
1 0.035  50.1  3.65  14.5  33.7 &lt;NA&gt;  &lt;NA&gt;     NA south
2 0.038  53.5  3.37  11.8  35   &lt;NA&gt;  &lt;NA&gt;     NA south
3 0.057  50    3.14  12.6  35.2 &lt;NA&gt;  &lt;NA&gt;     NA south
4 0.06   54.5  4.27  14.4  36.7 &lt;NA&gt;  &lt;NA&gt;     NA south
5 0.062  57.5  5.03  15.2  37.3 &lt;NA&gt;  &lt;NA&gt;     NA south
6 0.068  55.5  4.66  15.1  37   &lt;NA&gt;  &lt;NA&gt;     NA south</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
    age   hgt   wgt   bmi    hc gen   phb      tv reg  
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;
1  20.4  189.  59.8  16.8  55.2 &lt;NA&gt;  &lt;NA&gt;     NA west 
2  20.4  181.  67.2  20.5  56.6 &lt;NA&gt;  &lt;NA&gt;     NA north
3  20.8  189.  88    24.6  NA   &lt;NA&gt;  &lt;NA&gt;     NA west 
4  20.8  194.  75.4  20.1  NA   &lt;NA&gt;  &lt;NA&gt;     NA west 
5  20.8  189   78    21.8  59.9 &lt;NA&gt;  &lt;NA&gt;     NA north
6  21.2  182.  76.5  23.1  NA   &lt;NA&gt;  &lt;NA&gt;     NA east </code></pre>
</div>
</div>
<p>The functions <code>head()</code> and <code>tail()</code> are very useful functions. For example, from looking at both functions we can observe that the data are very likely sorted based on <code>age</code>.</p>
<hr>
<ol start="11" type="1">
<li><strong>Inspect the <code>boys</code> dataset with <code>str()</code>. Use one or more functions to find distributional summary information (at least information about the minimum, the maximum, the mean and the median) for all of the variables. Give the standard deviation for <code>age</code> and <code>bmi</code>. </strong> Tip: make use of the help (?) and help search (??) functionality in <code>R</code>.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [748 × 9] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ age: num [1:748] 0.035 0.038 0.057 0.06 0.062 0.068 0.068 0.071 0.071 0.073 ...
 $ hgt: num [1:748] 50.1 53.5 50 54.5 57.5 55.5 52.5 53 55.1 54.5 ...
 $ wgt: num [1:748] 3.65 3.37 3.14 4.27 5.03 ...
 $ bmi: num [1:748] 14.5 11.8 12.6 14.4 15.2 ...
 $ hc : num [1:748] 33.7 35 35.2 36.7 37.3 37 34.9 35.8 36.8 38 ...
 $ gen: chr [1:748] NA NA NA NA ...
 $ phb: chr [1:748] NA NA NA NA ...
 $ tv : num [1:748] NA NA NA NA NA NA NA NA NA NA ...
 $ reg: chr [1:748] "south" "south" "south" "south" ...
 - attr(*, "spec")=
  .. cols(
  ..   age = col_double(),
  ..   hgt = col_double(),
  ..   wgt = col_double(),
  ..   bmi = col_double(),
  ..   hc = col_double(),
  ..   gen = col_character(),
  ..   phb = col_character(),
  ..   tv = col_double(),
  ..   reg = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boys) <span class="co">#summary info</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      age              hgt              wgt              bmi       
 Min.   : 0.035   Min.   : 50.00   Min.   :  3.14   Min.   :11.77  
 1st Qu.: 1.581   1st Qu.: 84.88   1st Qu.: 11.70   1st Qu.:15.90  
 Median :10.505   Median :147.30   Median : 34.65   Median :17.45  
 Mean   : 9.159   Mean   :132.15   Mean   : 37.15   Mean   :18.07  
 3rd Qu.:15.267   3rd Qu.:175.22   3rd Qu.: 59.58   3rd Qu.:19.53  
 Max.   :21.177   Max.   :198.00   Max.   :117.40   Max.   :31.74  
                  NA's   :20       NA's   :4        NA's   :21     
       hc            gen                phb                  tv       
 Min.   :33.70   Length:748         Length:748         Min.   : 1.00  
 1st Qu.:48.12   Class :character   Class :character   1st Qu.: 4.00  
 Median :53.00   Mode  :character   Mode  :character   Median :12.00  
 Mean   :51.51                                         Mean   :11.89  
 3rd Qu.:56.00                                         3rd Qu.:20.00  
 Max.   :65.00                                         Max.   :25.00  
 NA's   :46                                            NA's   :522    
     reg           
 Length:748        
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(boys<span class="sc">$</span>age) <span class="co">#standard deviation for age</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.894052</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(boys<span class="sc">$</span>bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co">#standard deviation for bmi</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.053421</code></pre>
</div>
</div>
<p>Note that <code>bmi</code> contains 21 missing values, e.g.&nbsp;by looking at the summary information. Therefor we need to use <code>na.rm = T</code> to calculate the standard deviation on the observed cases only.</p>
<hr>
</section>
<section id="exercise-12-14-filtering-the-csv" class="level2">
<h2 class="anchored" data-anchor-id="exercise-12-14-filtering-the-csv">Exercise 12-14: Filtering the CSV</h2>
<ol start="12" type="1">
<li><strong>Select all boys that are 20 years or older. How many are there?</strong></li>
</ol>
<p>The logical operators (TRUE vs FALSE) are a very powerful tool in <code>R</code>. For example, we can just select the rows (respondents) in the data that are older than 20 by putting the logical operater within the row index of the dataset:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>boys2 <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">20</span>), ]</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p>or, alternatively (the tidy way),</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#Library to filter</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>boys2 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, age <span class="sc">&gt;=</span> <span class="dv">20</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<hr>
<ol start="13" type="1">
<li><strong>Select all boys that are older than 19, but younger than 19.5. How many are there?</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>boys3 <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&gt;</span> <span class="dv">19</span>) <span class="sc">&amp;</span> (boys<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="fl">19.5</span>), ]</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
</div>
<p>or, alternatively,</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>boys3 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, age <span class="sc">&gt;</span> <span class="dv">19</span>, age <span class="sc">&lt;</span> <span class="fl">19.5</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
</div>
<hr>
<ol start="14" type="1">
<li><strong>What is the mean age of boys younger than 15 years of age that do not live in region <code>north</code>?</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>age_subset <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="dv">15</span>) <span class="sc">&amp;</span> (boys<span class="sc">$</span>reg <span class="sc">!=</span> <span class="st">"north"</span>), ]<span class="sc">$</span>age</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(age_subset, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.044461</code></pre>
</div>
</div>
<p>or, alternatively,</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>age_subset <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, (age <span class="sc">&lt;</span> <span class="dv">15</span>), (reg <span class="sc">!=</span> <span class="st">"north"</span>))<span class="sc">$</span>age</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(age_subset, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.044461</code></pre>
</div>
</div>
<p>The mean age is 6.0444609 years</p>
</section>
<section id="exercises-15-17-visualization" class="level2">
<h2 class="anchored" data-anchor-id="exercises-15-17-visualization">Exercises 15-17: Visualization</h2>
<p>Download the file <code>example_csv.csv</code> from <a href="http://javier.science/R/#day-1-nov-12th">here</a> and add it to your data folder.</p>
<p>Open the file in your text editor to see how it looks. What is the first line?</p>
<ol start="15" type="1">
<li><strong>Read the file and save it with the name “df_events”.</strong> You’ll need to use the argument “skip” in the <code>read_delim()</code> function to skip the first line. Make sure it looks fine by printing the head.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 9 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
dbl (2): Time, Number

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>df_events <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"data/example_csv.csv"</span>, <span class="at">skip =</span> <span class="dv">1</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_events)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_events)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   Time Number
  &lt;dbl&gt;  &lt;dbl&gt;
1     1      1
2     3      2
3     4      3
4     5      4
5     7      5
6     9      6</code></pre>
</div>
</div>
<ol start="16" type="1">
<li><strong>Print summary statistics of the dataset</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_events)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Time            Number     
 Min.   : 1.000   Min.   :1.000  
 1st Qu.: 4.000   1st Qu.:2.000  
 Median : 7.000   Median :3.000  
 Mean   : 6.889   Mean   :3.111  
 3rd Qu.:10.000   3rd Qu.:4.000  
 Max.   :12.000   Max.   :6.000  </code></pre>
</div>
</div>
<ol start="17" type="1">
<li><strong>Plot the time vs the events using the function <code>plot</code> (you’ll learn a better way to plot with Gerko)</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_events<span class="sc">$</span>Time, df_events<span class="sc">$</span>Number)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Practical_B_walkthrough_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p>Today we have learned to use <code>R</code> at its basics. This offers tremendous flexibility, but may also be inefficient when our aim is some complex analysis, data operation of data manipulation. Doing advanced operations in basic <code>R</code> may require lots and lots of code. Next you will learn how to use R efficiently.</p>
<p>As you start using <code>R</code> in your own research, you will find yourself in need of packages that are not part of the default <code>R</code> installation. The beauty of <code>R</code> is that its functionality is community-driven. People can add packages to <code>CRAN</code> that other people can use and improve. Chances are that a function and/or package has been already developed for the analysis or operation you plan to carry out. If not, you are of course welcome to fill the gap by submitting your own package.</p>
<hr>
<p>End of practical</p>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb78" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Practical B"</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Javier Garcia-Bernardo (adapted from Gerko Vink)"</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/27/2023"</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-location: left</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 5</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: false</span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a><span class="fu"># Exercises</span></span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a>In this practical exercise we are going to play around with the different types of elements in R. </span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a>Click on the <span class="in">`Code`</span> buttons to see the solutions. Please really try before looking at the solution, and ask the instructor if something is not 100% clear.</span>
<span id="cb78-22"><a href="#cb78-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-23"><a href="#cb78-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-24"><a href="#cb78-24" aria-hidden="true" tabindex="-1"></a>First, create a new Quarto document for this practical (File -&gt; New File -&gt; Quarto document)</span>
<span id="cb78-25"><a href="#cb78-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-26"><a href="#cb78-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-27"><a href="#cb78-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 1-4: Vectors and matrices</span></span>
<span id="cb78-28"><a href="#cb78-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-29"><a href="#cb78-29" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-30"><a href="#cb78-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-31"><a href="#cb78-31" aria-hidden="true" tabindex="-1"></a><span class="ss"> 1. </span>**Make two vectors: one named <span class="in">`vec1`</span> with values 1 through 6 and one named <span class="in">`vec2`</span> with letters A through F. **</span>
<span id="cb78-34"><a href="#cb78-34" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-35"><a href="#cb78-35" aria-hidden="true" tabindex="-1"></a>vec1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb78-36"><a href="#cb78-36" aria-hidden="true" tabindex="-1"></a>vec2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>)</span>
<span id="cb78-37"><a href="#cb78-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-38"><a href="#cb78-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-39"><a href="#cb78-39" aria-hidden="true" tabindex="-1"></a>To create a vector we used <span class="in">`c()`</span>, which stands for 'concatenation'. It is just a series of numbers or letters. </span>
<span id="cb78-40"><a href="#cb78-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-41"><a href="#cb78-41" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-42"><a href="#cb78-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-43"><a href="#cb78-43" aria-hidden="true" tabindex="-1"></a><span class="ss"> 2. </span>**Create two matrices, one from <span class="in">`vec1`</span> and one from <span class="in">`vec2`</span>. The dimensions for both matrices are 3 rows by 2 columns. **</span>
<span id="cb78-44"><a href="#cb78-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-47"><a href="#cb78-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-48"><a href="#cb78-48" aria-hidden="true" tabindex="-1"></a>mat1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(vec1, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb78-49"><a href="#cb78-49" aria-hidden="true" tabindex="-1"></a>mat2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(vec2, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb78-50"><a href="#cb78-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-51"><a href="#cb78-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-52"><a href="#cb78-52" aria-hidden="true" tabindex="-1"></a>To create a matrix we used <span class="in">`matrix()`</span>. For a matrix we need to specify the dimensions (in this case 3 rows and 2 columns) and the input (in this case <span class="in">`vec1`</span> or <span class="in">`vec2`</span>) needs to match these dimensions. </span>
<span id="cb78-53"><a href="#cb78-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-54"><a href="#cb78-54" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-55"><a href="#cb78-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-56"><a href="#cb78-56" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Inspect your vectors and matrices. Are all numerical?**</span>
<span id="cb78-57"><a href="#cb78-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-60"><a href="#cb78-60" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-61"><a href="#cb78-61" aria-hidden="true" tabindex="-1"></a>vec1</span>
<span id="cb78-62"><a href="#cb78-62" aria-hidden="true" tabindex="-1"></a>vec2</span>
<span id="cb78-63"><a href="#cb78-63" aria-hidden="true" tabindex="-1"></a>mat1</span>
<span id="cb78-64"><a href="#cb78-64" aria-hidden="true" tabindex="-1"></a>mat2</span>
<span id="cb78-65"><a href="#cb78-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-66"><a href="#cb78-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-67"><a href="#cb78-67" aria-hidden="true" tabindex="-1"></a><span class="in">`vec1`</span> and <span class="in">`mat1`</span> contain numbers and <span class="in">`vec2`</span> and <span class="in">`mat2`</span> contain characters. </span>
<span id="cb78-68"><a href="#cb78-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-69"><a href="#cb78-69" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-70"><a href="#cb78-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-71"><a href="#cb78-71" aria-hidden="true" tabindex="-1"></a><span class="ss"> 4. </span>**Make a matrix from both `vec1` and `vec2` using cbind. Inspect this matrix using is.matrix().**</span>
<span id="cb78-72"><a href="#cb78-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-75"><a href="#cb78-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-76"><a href="#cb78-76" aria-hidden="true" tabindex="-1"></a>mat3b <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vec1, vec2)</span>
<span id="cb78-77"><a href="#cb78-77" aria-hidden="true" tabindex="-1"></a><span class="fu">is.matrix</span>(mat3b)</span>
<span id="cb78-78"><a href="#cb78-78" aria-hidden="true" tabindex="-1"></a>mat3b</span>
<span id="cb78-79"><a href="#cb78-79" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-80"><a href="#cb78-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-81"><a href="#cb78-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-82"><a href="#cb78-82" aria-hidden="true" tabindex="-1"></a>If one or more elements in the matrix represent characters, all other elements are also converted to characters. A matrix is just for either numeric or character elements. Notice that the second approach (the column bind approach from <span class="in">`mat3b`</span>) returns a matrix where the column names are already set to the name of the bound objects. </span>
<span id="cb78-83"><a href="#cb78-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-84"><a href="#cb78-84" aria-hidden="true" tabindex="-1"></a>To solve the problem of charactered numbers we can create a dataframe. A dataframe is essentially a matrix that allows for character elements. The use of a dataframe is often preferred over the use of a matrix in <span class="in">`R`</span>, except for purposes where pure numerical calculations are done, such as in matrix algebra. However, most datasets do contain character information and a dataframe would normally be your preferred choice when working with your own collected datasets in R. </span>
<span id="cb78-85"><a href="#cb78-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-86"><a href="#cb78-86" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-87"><a href="#cb78-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-88"><a href="#cb78-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 5-7: Data frames</span></span>
<span id="cb78-89"><a href="#cb78-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-90"><a href="#cb78-90" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Make a dataframe called `dat3` where `vec1` and `vec2` are both columns. Name the columns `V1` and `V2`, respectively. Use function `data.frame()`.**</span>
<span id="cb78-91"><a href="#cb78-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-94"><a href="#cb78-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-95"><a href="#cb78-95" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">V1 =</span> vec1, <span class="at">V2 =</span> vec2)</span>
<span id="cb78-96"><a href="#cb78-96" aria-hidden="true" tabindex="-1"></a>dat3</span>
<span id="cb78-97"><a href="#cb78-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-98"><a href="#cb78-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-99"><a href="#cb78-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-100"><a href="#cb78-100" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Select 1) the third row, 2) the second column and 3) the intersection of these two in the dataframe <span class="in">`dat3`</span> that you have created in Question 4. **</span>
<span id="cb78-103"><a href="#cb78-103" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-104"><a href="#cb78-104" aria-hidden="true" tabindex="-1"></a>dat3[<span class="dv">3</span>, ] <span class="co">#3rd row</span></span>
<span id="cb78-105"><a href="#cb78-105" aria-hidden="true" tabindex="-1"></a>dat3[, <span class="dv">2</span>] <span class="co">#2nd column</span></span>
<span id="cb78-106"><a href="#cb78-106" aria-hidden="true" tabindex="-1"></a>dat3<span class="sc">$</span>V2   <span class="co">#also 2nd column</span></span>
<span id="cb78-107"><a href="#cb78-107" aria-hidden="true" tabindex="-1"></a>dat3[<span class="dv">3</span>,<span class="dv">2</span>] <span class="co">#intersection</span></span>
<span id="cb78-108"><a href="#cb78-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-109"><a href="#cb78-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-110"><a href="#cb78-110" aria-hidden="true" tabindex="-1"></a>The <span class="in">`[3,2]`</span> index is very useful in 'R'. The first number (before the comma) represents the row and the second number (after the comma) represents the column. For a vector there are no two dimensions and only one dimension can be called. For example, <span class="in">`vec1[3]`</span> would yield <span class="in">`3`</span>. Try it. </span>
<span id="cb78-111"><a href="#cb78-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-112"><a href="#cb78-112" aria-hidden="true" tabindex="-1"></a>Columns can also be called by the <span class="in">`$`</span> sign, but only if a name has been assigned. With dataframes assigning names happens automatically. </span>
<span id="cb78-113"><a href="#cb78-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-114"><a href="#cb78-114" aria-hidden="true" tabindex="-1"></a>Note that <span class="in">`R`</span> automatically reports the values the character column can take. This means that the column is indeed a factor (a categorical variable - as it is supposed to be). A useful function to inspect the structure of a dataframe is <span class="in">`str()`</span>. Try running it. </span>
<span id="cb78-115"><a href="#cb78-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-118"><a href="#cb78-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-119"><a href="#cb78-119" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat3)</span>
<span id="cb78-120"><a href="#cb78-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-121"><a href="#cb78-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-122"><a href="#cb78-122" aria-hidden="true" tabindex="-1"></a>Inspecting the structure of your data is vital, as you probably have imported your data from some other source. If we, at a later stage, start analyzing our data without the correct measurement level, we may run into problems. One problem that often occurs is that categorical variables (factors in <span class="in">`R`</span>) are not coded as such. </span>
<span id="cb78-123"><a href="#cb78-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-124"><a href="#cb78-124" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-125"><a href="#cb78-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-126"><a href="#cb78-126" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Imagine that the first variable `V1` in our dataframe `dat3` is not coded correctly. Instead of digits, it should represent information about cities. Convert the variable to a factor and add the labels Utrecht (corresponding to value 1), New York (value 2), London (3), Singapore (4), Rome (5) and Cape Town (6).** </span>
<span id="cb78-129"><a href="#cb78-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-130"><a href="#cb78-130" aria-hidden="true" tabindex="-1"></a>dat3<span class="sc">$</span>V1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat3<span class="sc">$</span>V1, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Utrecht"</span>, <span class="st">"New York"</span>, <span class="st">"London"</span>, <span class="st">"Singapore"</span>, <span class="st">"Rome"</span>, <span class="st">"Capetown"</span>))</span>
<span id="cb78-131"><a href="#cb78-131" aria-hidden="true" tabindex="-1"></a>dat3</span>
<span id="cb78-132"><a href="#cb78-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-133"><a href="#cb78-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-134"><a href="#cb78-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 8-11: Read/explore CSV </span></span>
<span id="cb78-135"><a href="#cb78-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-136"><a href="#cb78-136" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-137"><a href="#cb78-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-138"><a href="#cb78-138" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Read the file `dataset_boys.csv`.** </span>
<span id="cb78-139"><a href="#cb78-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-140"><a href="#cb78-140" aria-hidden="true" tabindex="-1"></a>First create a folder "data" in your project. Then download it from <span class="co">[</span><span class="ot">here</span><span class="co">](https://javier.science/R/#day-1)</span> and add it to that folder (use Ctrl+S in the browser to download it).</span>
<span id="cb78-141"><a href="#cb78-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-142"><a href="#cb78-142" aria-hidden="true" tabindex="-1"></a>First you need to load the required library to read the CSV (<span class="in">`readr`</span>). You may need to install it first.</span>
<span id="cb78-143"><a href="#cb78-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-146"><a href="#cb78-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-147"><a href="#cb78-147" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c("readr"),repos = "http://cran.us.r-project.org")</span></span>
<span id="cb78-148"><a href="#cb78-148" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb78-149"><a href="#cb78-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-150"><a href="#cb78-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-151"><a href="#cb78-151" aria-hidden="true" tabindex="-1"></a>Then you can read the file using the function <span class="in">`read_delim()`</span> from the <span class="in">`readr`</span> library</span>
<span id="cb78-152"><a href="#cb78-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-155"><a href="#cb78-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-156"><a href="#cb78-156" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo=FALSE</span></span>
<span id="cb78-157"><a href="#cb78-157" aria-hidden="true" tabindex="-1"></a><span class="co">#Reading the file in the background</span></span>
<span id="cb78-158"><a href="#cb78-158" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"../common_datasets/dataset_boys.csv"</span>, <span class="at">delim=</span><span class="st">","</span>)</span>
<span id="cb78-159"><a href="#cb78-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-160"><a href="#cb78-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-161"><a href="#cb78-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-164"><a href="#cb78-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-165"><a href="#cb78-165" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval=FALSE</span></span>
<span id="cb78-166"><a href="#cb78-166" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"data/dataset_boys.csv"</span>, <span class="at">delim=</span><span class="st">","</span>)</span>
<span id="cb78-167"><a href="#cb78-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-168"><a href="#cb78-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-171"><a href="#cb78-171" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-172"><a href="#cb78-172" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boys)</span>
<span id="cb78-173"><a href="#cb78-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-174"><a href="#cb78-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-175"><a href="#cb78-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-176"><a href="#cb78-176" aria-hidden="true" tabindex="-1"></a>Alternatively, you can import datasets directly from the internet by running and loading the connection</span>
<span id="cb78-179"><a href="#cb78-179" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-180"><a href="#cb78-180" aria-hidden="true" tabindex="-1"></a><span class="co">#To update</span></span>
<span id="cb78-181"><a href="#cb78-181" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">url</span>(<span class="st">"https://javier.science/R/Contents/Material/common_datasets/dataset_boys.csv"</span>)</span>
<span id="cb78-182"><a href="#cb78-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-183"><a href="#cb78-183" aria-hidden="true" tabindex="-1"></a>In the above code we store the connection in object <span class="in">`con`</span> and then load the connectio.</span>
<span id="cb78-184"><a href="#cb78-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-185"><a href="#cb78-185" aria-hidden="true" tabindex="-1"></a>The <span class="in">`boys`</span> object will be added to your Global Environment. You can now use the <span class="in">`boys`</span> data by running</span>
<span id="cb78-186"><a href="#cb78-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-189"><a href="#cb78-189" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-190"><a href="#cb78-190" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(con, <span class="at">delim =</span> <span class="st">","</span>)</span>
<span id="cb78-191"><a href="#cb78-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-192"><a href="#cb78-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-193"><a href="#cb78-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-194"><a href="#cb78-194" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>**You can explore boys in several ways. In notebooks just write "boys" and run the chunk. You can also use the "Environment" menu to find the data "boys" and double click it. Alternatively write View(boys).**</span>
<span id="cb78-195"><a href="#cb78-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-196"><a href="#cb78-196" aria-hidden="true" tabindex="-1"></a>Using <span class="in">`View()`</span> is preferred for inspecting datasets that are large. <span class="in">`View()`</span> opens the dataset in a spreadsheet-like window (conform MS Excel, or SPSS). If you <span class="in">`View()`</span> your own datasets, you can not edit the datasets' contents. </span>
<span id="cb78-197"><a href="#cb78-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-198"><a href="#cb78-198" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-199"><a href="#cb78-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-200"><a href="#cb78-200" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>**Find out the dimensions of the <span class="in">`boys`</span> data set (use the function dim) and inspect the first and final 6 cases in the data set. **</span>
<span id="cb78-201"><a href="#cb78-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-202"><a href="#cb78-202" aria-hidden="true" tabindex="-1"></a>To do it numerically, find out what the dimensions of the boys dataset are. Use the function <span class="in">`dim()`</span></span>
<span id="cb78-205"><a href="#cb78-205" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-206"><a href="#cb78-206" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(boys)</span>
<span id="cb78-207"><a href="#cb78-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-208"><a href="#cb78-208" aria-hidden="true" tabindex="-1"></a>There are 748 cases on 9 variables. To select the first and last six cases, use</span>
<span id="cb78-211"><a href="#cb78-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-212"><a href="#cb78-212" aria-hidden="true" tabindex="-1"></a>boys[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, ]</span>
<span id="cb78-213"><a href="#cb78-213" aria-hidden="true" tabindex="-1"></a>boys[<span class="dv">743</span><span class="sc">:</span><span class="dv">748</span>, ]</span>
<span id="cb78-214"><a href="#cb78-214" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-215"><a href="#cb78-215" aria-hidden="true" tabindex="-1"></a>or, more efficiently:</span>
<span id="cb78-218"><a href="#cb78-218" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-219"><a href="#cb78-219" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boys)</span>
<span id="cb78-220"><a href="#cb78-220" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(boys)</span>
<span id="cb78-221"><a href="#cb78-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-222"><a href="#cb78-222" aria-hidden="true" tabindex="-1"></a>The functions <span class="in">`head()`</span> and <span class="in">`tail()`</span> are very useful functions. For example, from looking at both functions we can observe that the data are very likely sorted based on <span class="in">`age`</span>.</span>
<span id="cb78-223"><a href="#cb78-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-224"><a href="#cb78-224" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-225"><a href="#cb78-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-226"><a href="#cb78-226" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>**Inspect the <span class="in">`boys`</span> dataset with <span class="in">`str()`</span>. Use one or more functions to find distributional summary information (at least information about the minimum, the maximum, the mean and the median) for all of the variables. Give the standard deviation for <span class="in">`age`</span> and <span class="in">`bmi`</span>. ** Tip: make use of the help (?) and help search (??) functionality in <span class="in">`R`</span>. </span>
<span id="cb78-227"><a href="#cb78-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-230"><a href="#cb78-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-231"><a href="#cb78-231" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(boys)</span>
<span id="cb78-232"><a href="#cb78-232" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boys) <span class="co">#summary info</span></span>
<span id="cb78-233"><a href="#cb78-233" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(boys<span class="sc">$</span>age) <span class="co">#standard deviation for age</span></span>
<span id="cb78-234"><a href="#cb78-234" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(boys<span class="sc">$</span>bmi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co">#standard deviation for bmi</span></span>
<span id="cb78-235"><a href="#cb78-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-236"><a href="#cb78-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-237"><a href="#cb78-237" aria-hidden="true" tabindex="-1"></a>Note that <span class="in">`bmi`</span> contains 21 missing values, e.g. by looking at the summary information. Therefor we need to use <span class="in">`na.rm = T`</span> to calculate the standard deviation on the observed cases only.</span>
<span id="cb78-238"><a href="#cb78-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-239"><a href="#cb78-239" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-240"><a href="#cb78-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-241"><a href="#cb78-241" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 12-14: Filtering the CSV</span></span>
<span id="cb78-242"><a href="#cb78-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-243"><a href="#cb78-243" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>**Select all boys that are 20 years or older. How many are there?**</span>
<span id="cb78-244"><a href="#cb78-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-245"><a href="#cb78-245" aria-hidden="true" tabindex="-1"></a>The logical operators (TRUE vs FALSE) are a very powerful tool in <span class="in">`R`</span>. For example, we can just select the rows (respondents) in the data that are older than 20 by putting the logical operater within the row index of the dataset:</span>
<span id="cb78-248"><a href="#cb78-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-249"><a href="#cb78-249" aria-hidden="true" tabindex="-1"></a>boys2 <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">20</span>), ]</span>
<span id="cb78-250"><a href="#cb78-250" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys2)</span>
<span id="cb78-251"><a href="#cb78-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-252"><a href="#cb78-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-253"><a href="#cb78-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-254"><a href="#cb78-254" aria-hidden="true" tabindex="-1"></a>or, alternatively (the tidy way), </span>
<span id="cb78-257"><a href="#cb78-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-258"><a href="#cb78-258" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#Library to filter</span></span>
<span id="cb78-259"><a href="#cb78-259" aria-hidden="true" tabindex="-1"></a>boys2 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, age <span class="sc">&gt;=</span> <span class="dv">20</span>)</span>
<span id="cb78-260"><a href="#cb78-260" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys2)</span>
<span id="cb78-261"><a href="#cb78-261" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-262"><a href="#cb78-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-263"><a href="#cb78-263" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-264"><a href="#cb78-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-265"><a href="#cb78-265" aria-hidden="true" tabindex="-1"></a><span class="ss">13. </span>**Select all boys that are older than 19, but younger than 19.5. How many are there?**</span>
<span id="cb78-268"><a href="#cb78-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-269"><a href="#cb78-269" aria-hidden="true" tabindex="-1"></a>boys3 <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&gt;</span> <span class="dv">19</span>) <span class="sc">&amp;</span> (boys<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="fl">19.5</span>), ]</span>
<span id="cb78-270"><a href="#cb78-270" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys3)</span>
<span id="cb78-271"><a href="#cb78-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-272"><a href="#cb78-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-273"><a href="#cb78-273" aria-hidden="true" tabindex="-1"></a>or, alternatively, </span>
<span id="cb78-276"><a href="#cb78-276" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-277"><a href="#cb78-277" aria-hidden="true" tabindex="-1"></a>boys3 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, age <span class="sc">&gt;</span> <span class="dv">19</span>, age <span class="sc">&lt;</span> <span class="fl">19.5</span>)</span>
<span id="cb78-278"><a href="#cb78-278" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(boys3)</span>
<span id="cb78-279"><a href="#cb78-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-280"><a href="#cb78-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-281"><a href="#cb78-281" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-282"><a href="#cb78-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-283"><a href="#cb78-283" aria-hidden="true" tabindex="-1"></a><span class="ss">14. </span>**What is the mean age of boys younger than 15 years of age that do not live in region `north`?**</span>
<span id="cb78-284"><a href="#cb78-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-287"><a href="#cb78-287" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-288"><a href="#cb78-288" aria-hidden="true" tabindex="-1"></a>age_subset <span class="ot">&lt;-</span> boys[(boys<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="dv">15</span>) <span class="sc">&amp;</span> (boys<span class="sc">$</span>reg <span class="sc">!=</span> <span class="st">"north"</span>), ]<span class="sc">$</span>age</span>
<span id="cb78-289"><a href="#cb78-289" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(age_subset, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb78-290"><a href="#cb78-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-291"><a href="#cb78-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-292"><a href="#cb78-292" aria-hidden="true" tabindex="-1"></a>or, alternatively, </span>
<span id="cb78-295"><a href="#cb78-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-296"><a href="#cb78-296" aria-hidden="true" tabindex="-1"></a>age_subset <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(boys, (age <span class="sc">&lt;</span> <span class="dv">15</span>), (reg <span class="sc">!=</span> <span class="st">"north"</span>))<span class="sc">$</span>age</span>
<span id="cb78-297"><a href="#cb78-297" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(age_subset, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb78-298"><a href="#cb78-298" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-299"><a href="#cb78-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-300"><a href="#cb78-300" aria-hidden="true" tabindex="-1"></a>The mean age is <span class="in">`r mean(boys$age[boys$age &lt; 15 &amp; boys$reg != "north" ], na.rm = TRUE)`</span> years</span>
<span id="cb78-301"><a href="#cb78-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-302"><a href="#cb78-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-303"><a href="#cb78-303" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercises 15-17:  Visualization</span></span>
<span id="cb78-304"><a href="#cb78-304" aria-hidden="true" tabindex="-1"></a>Download the file <span class="in">`example_csv.csv`</span> from <span class="co">[</span><span class="ot">here</span><span class="co">](http://javier.science/R/#day-1-nov-12th)</span> and add it to your data folder.</span>
<span id="cb78-305"><a href="#cb78-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-306"><a href="#cb78-306" aria-hidden="true" tabindex="-1"></a>Open the file in your text editor to see how it looks. What is the first line?</span>
<span id="cb78-307"><a href="#cb78-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-308"><a href="#cb78-308" aria-hidden="true" tabindex="-1"></a><span class="ss">15. </span>**Read the file and save it with the name "df_events".** You'll need to use the argument "skip" in the <span class="in">`read_delim()`</span> function to skip the first line. Make sure it looks fine by printing the head.</span>
<span id="cb78-309"><a href="#cb78-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-312"><a href="#cb78-312" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-313"><a href="#cb78-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo=FALSE</span></span>
<span id="cb78-314"><a href="#cb78-314" aria-hidden="true" tabindex="-1"></a><span class="co">#Reading data in background</span></span>
<span id="cb78-315"><a href="#cb78-315" aria-hidden="true" tabindex="-1"></a>df_events <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"../common_datasets/example_csv.csv"</span>, <span class="at">skip =</span> <span class="dv">1</span>)</span>
<span id="cb78-316"><a href="#cb78-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-317"><a href="#cb78-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-320"><a href="#cb78-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-321"><a href="#cb78-321" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval=FALSE</span></span>
<span id="cb78-322"><a href="#cb78-322" aria-hidden="true" tabindex="-1"></a>df_events <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_delim</span>(<span class="st">"data/example_csv.csv"</span>, <span class="at">skip =</span> <span class="dv">1</span>)</span>
<span id="cb78-323"><a href="#cb78-323" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_events)</span>
<span id="cb78-324"><a href="#cb78-324" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-325"><a href="#cb78-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-328"><a href="#cb78-328" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-329"><a href="#cb78-329" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_events)</span>
<span id="cb78-330"><a href="#cb78-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-331"><a href="#cb78-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-332"><a href="#cb78-332" aria-hidden="true" tabindex="-1"></a><span class="ss">16. </span>**Print summary statistics of the dataset**</span>
<span id="cb78-335"><a href="#cb78-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-336"><a href="#cb78-336" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_events)</span>
<span id="cb78-337"><a href="#cb78-337" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-338"><a href="#cb78-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-339"><a href="#cb78-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-340"><a href="#cb78-340" aria-hidden="true" tabindex="-1"></a><span class="ss">17. </span>**Plot the time vs the events using the function `plot` (you'll learn a better way to plot with Gerko)**</span>
<span id="cb78-343"><a href="#cb78-343" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb78-344"><a href="#cb78-344" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_events<span class="sc">$</span>Time, df_events<span class="sc">$</span>Number)</span>
<span id="cb78-345"><a href="#cb78-345" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb78-346"><a href="#cb78-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-347"><a href="#cb78-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-348"><a href="#cb78-348" aria-hidden="true" tabindex="-1"></a>--- </span>
<span id="cb78-349"><a href="#cb78-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-350"><a href="#cb78-350" aria-hidden="true" tabindex="-1"></a>Today we have learned to use <span class="in">`R`</span> at its basics. This offers tremendous flexibility, but may also be inefficient when our aim is some complex analysis, data operation of data manipulation. Doing advanced operations in basic <span class="in">`R`</span> may require lots and lots of code. Next you will learn how to use R efficiently. </span>
<span id="cb78-351"><a href="#cb78-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-352"><a href="#cb78-352" aria-hidden="true" tabindex="-1"></a>As you start using <span class="in">`R`</span> in your own research, you will find yourself in need of packages that are not part of the default <span class="in">`R`</span> installation. The beauty of <span class="in">`R`</span> is that its functionality is community-driven. People can add packages to <span class="in">`CRAN`</span> that other people can use and improve. Chances are that a function and/or package has been already developed for the analysis or operation you plan to carry out. If not, you are of course welcome to fill the gap by submitting your own package. </span>
<span id="cb78-353"><a href="#cb78-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-354"><a href="#cb78-354" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb78-355"><a href="#cb78-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-356"><a href="#cb78-356" aria-hidden="true" tabindex="-1"></a>End of practical</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>